config/routes.rb
Rails.application.routes.draw do
 
 
get "login" => "user_sessions#new", :as => :login
get "signup" => "users#new", :as => "signup"
  post 'logout' => 'user_sessions#destroy', :as => :logout
  
  resource :user_sessions 
  resources :users
 

  get 'static_pages/about'

  get 'static_pages/contact'

  resources :criteria

  root 'static_pages#home'

end

app/models/criterium.rb
class Criterium < ActiveRecord::Base
  has_attached_file :file_upload, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :file_upload, :content_type => /\Aimage\/.*\Z/
  
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/criteria_controller.rb
class CriteriaController < ApplicationController

  before_action :set_criterium, only: [:show, :edit, :update, :destroy]

  # GET /criteria
  # GET /criteria.json
  def index
    @criteria = Criterium.all
  end

  # GET /criteria/1
  # GET /criteria/1.json
  def show
  end

  # GET /criteria/new
  def new
    @criterium = Criterium.new
  end

  # GET /criteria/1/edit
  def edit
  end

  # POST /criteria
  # POST /criteria.json
  def create
    @criterium = Criterium.new(criterium_params)

    respond_to do |format|
      if @criterium.save
        format.html { redirect_to @criterium, notice: 'Criterium was successfully created.' }
        format.json { render :show, status: :created, location: @criterium }
      else
        format.html { render :new }
        format.json { render json: @criterium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /criteria/1
  # PATCH/PUT /criteria/1.json
  def update
    respond_to do |format|
      if @criterium.update(criterium_params)
        format.html { redirect_to @criterium, notice: 'Criterium was successfully updated.' }
        format.json { render :show, status: :ok, location: @criterium }
      else
        format.html { render :edit }
        format.json { render json: @criterium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /criteria/1
  # DELETE /criteria/1.json
  def destroy
    @criterium.destroy
    respond_to do |format|
      format.html { redirect_to criteria_url, notice: 'Criterium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_criterium
      @criterium = Criterium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def criterium_params
      params.require(:criterium).permit(:school_name, :evaluator_name, :evaluated_name, :subject, :sudent_id, :employee_id, :eval_id, :vanguard, :class_period, :grade, :student_employee, :notes, :pl1, :pl2, :pl3, :pr1, :pr2, :pr3, :pr4, :pr5, :pr6, :pr7, :pr8, :pr9, :i1, :i2, :i3, :i4, :i5, :i6, :i7, :i8, :i9, :i10, :file_upload)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
   def new
   
  end

  def create
     user = login(params[:email], params[:password], params[:remember_me])
    if user
      redirect_to criteria_url, :notice => "You are Logged in"
    else
      redirect_to :login, :alert => "Invalid Username or Password!"
     
    end
  end
  
  def destroy
  
  redirect_to root_url, :notice => "Succesfully Logged out"
   logout 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/criteria_helper.rb
module CriteriaHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/criteria/_form.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-7">
<%= form_for @criterium, :html => { :class => "form-horizontal criterium" } do |f| %>

    <% if @criterium.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@criterium.errors.count, "error") %> prohibited this criterium from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @criterium.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :school_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :school_name, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:school_name]) %>
  </div>
  <div class="control-group">
    <%= f.label :evaluator_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :evaluator_name, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:evaluator_name]) %>
  </div>
  <div class="control-group">
    <%= f.label :evaluated_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :evaluated_name, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:evaluated_name]) %>
  </div>
  <div class="control-group">
    <%= f.label :subject, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :subject, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:subject]) %>
  </div>
  <div class="control-group">
    <%= f.label :sudent_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :sudent_id, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:sudent_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :employee_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :employee_id, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:employee_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :eval_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :eval_id, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:eval_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :vanguard, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :vanguard, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:vanguard]) %>
  </div>
  <div class="control-group">
    <%= f.label :class_period, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :class_period, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:class_period]) %>
  </div>
  <div class="control-group">
    <%= f.label :grade, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :grade, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:grade]) %>
  </div>
  <div class="control-group">
    <%= f.label :student_employee, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :student_employee, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:student_employee]) %>
  </div>
  <div class="control-group">
    <%= f.label :pl1, :class => 'control-label' %> <h5>Develops student leraning goals.</h5>
    <div class="controls">
      <%= f.text_field :pl1, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:pl1]) %>
  </div>
  <div class="control-group">
    <%= f.label :pl2, :class => 'control-label' %> <h5>Collects, tracks, and uses student data to drive instruction.</h5>
    <div class="controls">
      <%= f.text_field :pl2, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:pl2]) %>
  </div>
  <div class="control-group">
    <%= f.label :pl3, :class => 'control-label' %> <h5>Design effective lesson plans,units,and assessments.</h5>
    <div class="controls">
      <%= f.text_field :pl3, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:pl3]) %>
  </div>
  <div class="control-group">
    <%= f.label :i1, :class => 'control-label' %> <h5>Facilities organized, student-centered, objective-driven lessons.</h5>
    <div class="controls">
      <%= f.text_field :i1, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:i1]) %>
  </div>
  <div class="control-group">
    <%= f.label :i2, :class => 'control-label' %> <h5>Checks for student understanding and responds to student misunderstanding.</h5>
    <div class="controls">
      <%= f.text_field :i2, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:i2]) %>
  </div>
  <div class="control-group">
    <%= f.label :i3, :class => 'control-label' %> <h5>Differentiates instruction for student needs by employing a variety of instructional strategies.</h5>
    <div class="controls">
      <%= f.text_field :i3, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:i3]) %> 
  </div>
  <div class="control-group">
    <%= f.label :i4, :class => 'control-label' %> <h5>Engages students in work that develops higher-level thinking skills.</h5>
    <div class="controls">
      <%= f.text_field :i4, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:i4]) %>
  </div>
  <div class="control-group">
    <%= f.label :i5, :class => 'control-label' %> <h5>Maximizes instructional time.</h5>
    <div class="controls">
      <%= f.text_field :i5, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:i5]) %>
  </div>
  <div class="control-group">
    <%= f.label :i6, :class => 'control-label' %> <h5>Communicates content and concepts to students.</h5>
    <div class="controls">
      <%= f.text_field :i6, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:i6]) %>
  </div>
  <div class="control-group">
    <%= f.label :i7, :class => 'control-label' %> <h5>Promotes high academic expectations for students.</h5>
    <div class="controls">
      <%= f.text_field :i7, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:i7]) %>
  </div>
  <div class="control-group">
    <%= f.label :i8, :class => 'control-label' %> <h5>Students actively participating in lesson activities.</h5>
    <div class="controls">
      <%= f.text_field :i8, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:i8]) %>
  </div>
  <div class="control-group">
    <%= f.label :i9, :class => 'control-label' %> <h5>Sets and implements disciplene management procedures.</h5>
    <div class="controls">
      <%= f.text_field :i9, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:i9]) %>
  </div>
  <div class="control-group">
    <%= f.label :i10, :class => 'control-label' %> <h5>Builds a positive and respectful classroom enviornment.</h5>
    <div class="controls">
      <%= f.text_field :i10, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:i10]) %>
  </div>

 <div class="control-group">
 <%= f.label :pr1, :class => 'control-label' %><h5>Complies with policies and procedures at school.</h5>
    <div class="controls">
      <%= f.text_field :pr1, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:pr1]) %>
  </div>

 <div class="control-group">
 <%= f.label :pr2, :class => 'control-label' %><h5>Treats colleagues with respect throughout all aspects of work.</h5>
    <div class="controls">
      <%= f.text_field :pr2, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:pr2]) %>
  </div>
 <div class="control-group">
 <%= f.label :pr3, :class => 'control-label' %> <h5>Complies with teacher attendance policies.</h5>
    <div class="controls">
      <%= f.text_field :pr3, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:pr3]) %>
  </div>
 <div class="control-group">
 <%= f.label :pr4, :class => 'control-label' %> <h5>Dresses professionally according to school dress policy.</h5>
    <div class="controls">
      <%= f.text_field :pr4, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:pr4]) %>
  </div>
 <div class="control-group">
 <%= f.label :pr5, :class => 'control-label' %> <h5>Collaborates with coleagues.</h5>
    <div class="controls">
      <%= f.text_field :pr5, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:pr5]) %>
  </div>
<div class="control-group">
 <%= f.label :pr6, :class => 'control-label' %> <h5>Implements school rules.</h5>
    <div class="controls">
      <%= f.text_field :pr6, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:pr6]) %>
  </div>

<div class="control-group">
 <%= f.label :pr7, :class => 'control-label' %> <h5>Communicates with parents throughout the year.</h5>
    <div class="controls">
      <%= f.text_field :pr7, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:pr7]) %>
  </div>

<div class="control-group">
 <%= f.label :pr8, :class => 'control-label' %> <h5>Seeks feedback in order to improve performance.</h5>
    <div class="controls">
      <%= f.text_field :pr8, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:pr8]) %>
  </div>

<div class="control-group">
 <%= f.label :pr9, :class => 'control-label' %> <h5>Participates in proffessional development and applies learning.</h5>
    <div class="controls">
      <%= f.text_field :pr9, :class => 'form-control' %>
    </div>
    <%= error_span(@criterium[:pr9]) %>
  </div>
 </div>   
<div class="col-md-3 jumbotron">
<div class="control-group">
  <%= f.label :note, :class => 'control-label' %> 
    <div class="controls">
      <%= f.text_area :note, :class => 'form-control' %>
    </div>
  <%= error_span(@criterium[:note]) %>
  </div>
    
     <%= f.file_field :file_upload %>
    </div>
</div>
<br>

<br>
<%= f.submit nil, :class => 'btn btn-success' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            criteria_path, :class => 'btn btn-default' %>

<% end %>
   

app/views/criteria/edit.html.erb
<%- model_class = Criterium -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/criteria/index.html.erb
<div class="row">
  <div class="col-md-10 col-md-push-1">
  <%- model_class = Criterium -%>
  <div class="page-header">
    <h1><%=t '.title', :default => "Evaluations".pluralize.titleize %></h1>
  </div>
</div>
 <div class="col-md-10 col-md-push-2">
  <div class="table_container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:id) %></th>
        <th><%= model_class.human_attribute_name(:school_name) %></th>

        <th><%= model_class.human_attribute_name(:subject) %></th>
        <th><%= model_class.human_attribute_name(:eval_id) %></th>
       

        <th><%= model_class.human_attribute_name(:created_at) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @criteria.each do |criterium| %>
        <tr>
          <td><%= link_to criterium.id, criterium_path(criterium) %></td>
          <td><%= criterium.school_name %></td>
       
          <td><%= criterium.subject %></td>
       
          <td><%= criterium.eval_id %></td>

          <td><%=l criterium.created_at %></td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
      edit_criterium_path(criterium), :class => 'btn btn-success btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        criterium_path(criterium),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_criterium_path,
              :class => 'btn btn-primary' %>
  </div>
</div>

app/views/criteria/new.html.erb
<%- model_class = Criterium -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Evaluation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Teacher Appraisals</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "About", static_pages_about_path %></li>
                <li><%= link_to "Contact", static_pages_contact_path  %></li>
                <% if current_user %>
                <li><%= link_to "Evaluations", criteria_path  %></li>
                <% end %>
                <li> 
                      <% if current_user %>
                            
                            <%= link_to "Logout", :logout, method: :post %>
                           <% else %>
                               
                               <%= link_to "Login", :login %>
                           <% end %></li> 
              </ul>
            </div>
          </div>
        </nav>
  
<%= yield %>

      <!-- FOOTER -->
      <footer>
<!--         <p class="pull-right"><a href="#">Back to top</a></p> -->
        <p>© 2014 Company, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
      </footer>
</body>
</html>

app/views/static_pages/about.html.erb
<h1>About Page</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget erat ipsum. Aliquam felis ante, elementum at massa eu, consequat sodales nibh. Fusce sagittis quis mi vel auctor. Proin vel dolor luctus, auctor enim in, malesuada urna. Nulla facilisi. Praesent lectus orci, elementum eget porttitor ut, eleifend lacinia urna. Maecenas pulvinar lacinia ex, eget euismod nibh convallis a. Ut volutpat mauris ante, venenatis dignissim sem feugiat a. Vivamus varius justo in est sollicitudin, in ullamcorper nisi gravida. Nam tincidunt arcu erat. Sed consectetur nisl est, vel condimentum ante volutpat ut. Sed egestas id dolor nec sagittis. Vestibulum purus orci, ullamcorper eu vulputate eget, ultrices sit amet elit. Suspendisse lacus lorem, imperdiet vitae euismod id, feugiat vitae felis. Quisque auctor orci ac est venenatis placerat.</p>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget erat ipsum. Aliquam felis ante, elementum at massa eu, consequat sodales nibh. Fusce sagittis quis mi vel auctor. Proin vel dolor luctus, auctor enim in, malesuada urna. Nulla facilisi. Praesent lectus orci, elementum eget porttitor ut, eleifend lacinia urna. Maecenas pulvinar lacinia ex, eget euismod nibh convallis a. Ut volutpat mauris ante, venenatis dignissim sem feugiat a. Vivamus varius justo in est sollicitudin, in ullamcorper nisi gravida. Nam tincidunt arcu erat. Sed consectetur nisl est, vel condimentum ante volutpat ut. Sed egestas id dolor nec sagittis. Vestibulum purus orci, ullamcorper eu vulputate eget, ultrices sit amet elit. Suspendisse lacus lorem, imperdiet vitae euismod id, feugiat vitae felis. Quisque auctor orci ac est venenatis placerat.</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>
<%= form_tag user_sessions_path do %>
<div class="form-horizontal login-form">
  <div class="form-group">
      <div class="col-sm-offset-1 col-sm-10 input-group input-group-lg">
      <%= label_tag :email %>
    
     <%= text_field_tag :email, params[:email], :class => 'form-control',:type => "email", :placeholder => 'Email Address' %>
    </div>
  </div>
    
  <div class="form-group">
   <div class="col-sm-offset-1  col-sm-10 input-group input-group-lg">   
      <%= label_tag :password %>
    
      <%= text_field_tag :password, params[:password], :class => 'form-control',:type => "password", :placeholder => 'Password'  %>
    </div>
  </div>
  <br><br>
  <div class="form-group">
       <div class="col-sm-offset-1 col-sm-10 input-group input-group-lg">
        <%= submit_tag "Log in",:class => 'btn btn-lg btn-success'%>&nbsp;
        
      </div>
  </div>
</div>  
    
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  # app/views/users/_form.html.erb
<div class="field">
   <%= f.label :password %><br />
   <%= f.password_field :password %>
</div>
<div class="field">
   <%= f.label :password_confirmation %><br />
   <%= f.password_field :password_confirmation %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Crypted password</th>
      <th>Salt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.crypted_password %></td>
        <td><%= user.salt %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Crypted password:</strong>
  <%= @user.crypted_password %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @user.salt %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>